CREATE TABLE resume (
    uuid      VARCHAR PRIMARY KEY,
    full_name VARCHAR NOT NULL
);
CREATE TABLE contact (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_uuid VARCHAR REFERENCES resume (uuid) ON DELETE CASCADE,
    type        VARCHAR NOT NULL,
    value       VARCHAR NOT NULL
);