CREATE TABLE resume
(
    uuid      VARCHAR PRIMARY KEY,
    full_name VARCHAR NOT NULL
);
CREATE TABLE contact
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_uuid VARCHAR REFERENCES resume (uuid) ON DELETE CASCADE,
    type        VARCHAR NOT NULL,
    value       VARCHAR NOT NULL
);
CREATE UNIQUE INDEX contact_uuid_type_index
    ON contact (resume_uuid, type);
CREATE TABLE section
(
    id          INT GENERATED by default as identity PRIMARY KEY,
    type        VARCHAR NOT NULL,
    title       VARCHAR NOT NULL,
    resume_uuid varchar REFERENCES resume (uuid) ON DELETE CASCADE
);
CREATE UNIQUE INDEX section_idx
    ON section (resume_uuid, type);